package textversion;

import java.io.File;
import java.util.List;

public class TextFileInput {
	
	public TextFileInput() {
		// put it here just for more clarity, it is auto-generated by java machine
	}

	public static void main(String[] args) {
		TextFileInput fileInput = new TextFileInput();
		fileInput.run(args);
	}
	
	private void run(String[] args) {
		
		String sourceFilePath = "E:\\Github\\Personal-Projects\\Java_projects\\JeanWorkspace\\StudentReport\\resources\\InputTest.txt";  
		String destinationPath = "E:\\Github\\Personal-Projects\\Java_projects\\JeanWorkspace\\StudentReport";
		String inLineSeparator = ",";
		
		if (args.length == 2) { //receive input file path from in-line argument
			sourceFilePath = args[0]; 
			destinationPath = args[1];
		}
		
		File classGradesReport = new File(destinationPath,  "ClassReport_byGrades.txt");
		File classNameReport = new File(destinationPath, "ClassReport_Alphabetic.txt");
		
		File sourceFile = new File(sourceFilePath); //create a file with given name  
		try { 
			List<Student> studentsList = FileParser.readDataFromFile(sourceFile, inLineSeparator); 
			
			boolean sortAscending = false;
			GroupByGrades.writeStudentsByGrades(studentsList, classGradesReport, sortAscending);
			GroupAlphabetically.writeStudentsAlphabetically(studentsList, classNameReport, sortAscending);
			
		}
		catch (Exception exception1) { //print all exception in same catch because all of them are same treatment
			exception1.printStackTrace();
		}
	
	} 	
}
